### ISSUE TITLE
"Download Brackets without Extract" link blocked by HTTPS Everywhere on Firefox

### ISSUE THREAD

**Issue by anewuser** [adobe/brackets.io#138] opened 2015-02-19 23:40 UTC
The "Download Brackets without Extract" link doesn't work for me (Firefox 35.0.1 on Windows). I opened the console and found this:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://s3.amazonaws.com/files.brackets.io/updates/stable/en.json?_=1424389017263. This can be fixed by moving the resource to the same domain or enabling CORS.

**Comment by peterflynn** [comment] 2015-02-20 00:13
I suspect that error is unrelated -- clear your console after the page is loaded, then click the button, then see if anything new has appeared in the console.  If not, then maybe use the FF dev tools to debug into `logAndGo()` and see why clicking the link isn't working.

The CORS error is very strange though -- that URL _does_ respond with `Access-Control-Allow-Origin: *` already (otherwise it wouldn't work in any browser).  Do you have any FF extensions installed (adblockers, etc.) that might be affecting this?

**Comment by peterflynn** [comment] 2015-02-20 00:25
Hmm that link works for me in Firefox 35.0.1 on Mac -- and I don't see that error in the console either.  Maybe try making a clean FF profile (no extensions, empty cache, default settings) and check if you see the same thing there or not.

**Comment by anewuser** [comment] 2015-02-20 04:43
I'm sorry for not trying the Firefox "safe mode" before posting here. 

This error is indeed caused by an extension:  [HTTPS-Everywhere](https://www.eff.org/https-everywhere). Disabling it makes the download work.

**Comment by peterflynn** [comment] 2015-03-01 08:47
Can you use Firefox dev tools to capture a log of the network when loading the page, and then when clicking the button?  That should show which request is failing.

**Comment by anewuser** [comment] 2015-03-01 21:40
The only error that appears is the one I included in my first post. HTTPS-Everywhere is an extension that redirects requests to domains in a pre-built list to their HTTPS versions. If you want, I can report this to its developers.

**Comment by PlanetVaster** [comment] 2015-03-04 23:19
Guess it's solved you should close this now

**Comment by peterflynn** [comment] 2015-03-05 00:10
@anewuser Right, but I have no idea which domains are in their whitelist, so I don't know which network requests were modified from what the page was expecting.  The Firefox dev tools has a Network tab -- if you open that and then load brackets.io, you should be able to go down the list and see (a) which items were loaded via `https://` URLs, and (b) which items had an error or redirect.

**Comment by marcelgerber** [comment] 2015-03-05 20:31
I've installed the HTTPS Everywhere extension and actually, the issue _is_ caused by the CORS issue that is also printed to console. The current Brackets Release cannot be determined without downloading the JSON file, so HTTPS Everywhere breaks the website by breaking CORS.

The CORS issue is probably https://github.com/EFForg/https-everywhere/issues/49.

**Comment by peterflynn** [comment] 2015-03-05 20:45
@MarcelGerber Ah, cool!  It didn't even occur to me that the extension could be breaking CORS directly, rather than just changing URLs.  Definitely a problem with the extension itself then -- nothing wrong with our page...

**Comment by marcelgerber** [comment] 2015-03-05 20:49
Yeah, but I have a fix up (imo a improvement anyway) to fix the extension.

**Closed as completed** 2017-05-08 14:40 UTC

**Comment by scheinercc** [comment] 2017-09-29 13:02
In case someone else lands here - related FF bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1149250
